### PR TITLE
docs: add nixpkgs/regal to the adopters list

### PR DESCRIPTION
**Pull request by rinx**
I've added a link to the package on nixpkgs.

### CODE REVIEW

**Comment by charlieegan3** [comment]
Hi @rinx, thanks so much for this! I hadn't even realised that Regal was on nixpkgs.

We actually pushed out an update just yesterday, [`v0.24.0`](https://github.com/StyraInc/regal/releases/tag/v0.24.0), which has some new features. I'll see if I can get that updated to return the love.

**Comment by charlieegan3** [comment]
Hmm, it looks like the updates are automated in some way? https://github.com/NixOS/nixpkgs/pull/308599. Is there a way I can trigger the bot to run the update?

**Comment by rinx** [comment]
@charlieegan3 Thanks for reviewing!

There's already a PR to update to `0.24.0`.
https://github.com/NixOS/nixpkgs/pull/327824

**Comment by anderseknert** [comment]
Very nice. Thanks @rinx!

**Comment by charlieegan3** [comment]
Ahh very cool, less work for everyone! 🙂

**Pull request merged**
