### PR TITLE
lsp: Make server messages compliant

### PR DESCRIPTION
**Pull request by charlieegan3**
Fixes https://github.com/StyraInc/regal/issues/585

Changes:
- make sure that errors are 1 not 0s in severity codes
- Use code desc for Href to lint docs

TODO:
- [ ] wait for some confirmation from reporter of #585  that this works ok

### CODE REVIEW

**Review by anderseknert — APPROVED** [review]
👍

**Review by srenatus — APPROVED** [review]

**Comment by anderseknert** [comment]
Cutting a release tomorrow, so let's get this included. @folliehiyuki do let us know if this did not resolve the issue and we'll get back to it immediately.

**Comment by folliehiyuki** [comment]
I can confirm the diagnostic messages seem correct now. Here is a few screenshots with my setup.

On a file with found issues:



with syntax error or being an empty file:

**Comment by folliehiyuki** [comment]
Also, I've opened https://github.com/neovim/nvim-lspconfig/pull/3071 to include basic `regal` setup into the common LSP configuration of Neovim.

**Comment by charlieegan3** [comment]
@folliehiyuki thanks so much for checking this over and adding it to the nvim-lspconfig repo too. Much appreciated! 👏 

`nvim-lspconfig` is the default way to use Language Servers from Neovim? I'm just trying to work out the best message for the notes here: https://docs.styra.com/regal/editor-support

**Comment by folliehiyuki** [comment]
> `nvim-lspconfig` is the default way to use Language Servers from Neovim?

Yes, it's a Neovim plugin that most (if not all) people use as a base to configure their LSP servers (and other LSP-related settings).

This is a snippet to enable Regal LSP with default settings, judging that you already have `regal` and the plugin installed:
```lua
require('lspconfig').regal.setup()
```

**Comment by charlieegan3** [comment]
That's great, I think we can get a note in the docs for that! Thanks so much for this info as we're not neovim users it's hard to be sure on some of these points!

**Comment by charlieegan3** [comment]
PR for the docs: https://github.com/StyraInc/regal/pull/604

**Pull request merged**
