### PR TITLE
docs/editor: write about nvim-dap

### PR DESCRIPTION
**Pull request by rinx**
I wrote a brief explanation about Neovim's DAP support.

### CODE REVIEW

**Comment by charlieegan3** [comment]
Hey @rinx! this is an awesome and very welcome addition to the editor support for Regal! After some fiddling with lazy vim I was able to get this working nicely!

https://github.com/user-attachments/assets/769bfc73-54e2-4b4c-880e-47f250d08e76

We're doing some final adjustments as we prep to release the VS Code client soon, however I'll be sure to highlight your project in that announcement too.

p.s. looking forward to being able to install https://github.com/rinx/nvim-dap-rego as a nix package! 😎

**Review by charlieegan3 — APPROVED** [review]

**Comment by srenatus** [comment]
Nice touch with Fennel --> Lua in that package, too ✨

**Comment by anderseknert** [comment]
This is awesome. Thanks a lot @rinx 👏

**Comment by rinx** [comment]
Thanks for accepting this pull request. :smile:

> p.s. looking forward to being able to install https://github.com/rinx/nvim-dap-rego as a nix package! 😎

That's great idea! I'll try to do it.

**Comment by charlieegan3** [comment]
❤️ 

I've been enjoying using home-manager to install [vimPlugins](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=vimPlugins) from nixpkgs. I find it works really well so far.

**Pull request merged**
