### PR TITLE
update eopa caps and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by srenatus**

### CODE REVIEW

**Review by charlieegan3 — APPROVED** [review]
This might be a good PR check to run? We seem to have gotten a bit behind...

**Comment by srenatus** [comment]
Not sure -- having unrelated PRs fail because there happens to have been a new EOPA version isn't ideal... we could have a nightly run just do the commit? 🤔

**Comment by anderseknert** [comment]
Something scheduled sounds good to me

**Comment by srenatus** [comment]
https://github.com/StyraInc/regal/pull/1158

**Pull request merged**
