### PR TITLE
docs: Fix spelling mistakes

### PR DESCRIPTION
**Pull request by charlieegan3**
There were a number of spelling mistakes in the documentation. This PR fixes them as the spelling will soon be enforced in docs.styra.com.

### CODE REVIEW

**Review by anderseknert — APPROVED** [review]
Thanks a lot! Would it not make sense to run the same spell checker in this repo? That way we'd be able to catch mistakes where they happen. But of course, not blocking.

**Comment by charlieegan3** [comment]
Indeed, I would like to have a spell checker here too. I _think_ the way to go is to not check the regal spelling in docs.styra.com eventually and check here instead. I have a think about the best way to do it.

**Comment by anderseknert** [comment]
Inspires me to think about spell checking as a Regal linter rule too :) Might be some good Go library for that we could turn into a custom function, and then have at least an optional rule that could spell check comments, metadata or even code if desired.

**Comment by charlieegan3** [comment]
💯 checking spelling in comments would be great.

**Pull request merged**
