### PR TITLE
Have `redundant-existence-check` include function args

### LINKED ISSUE #1226: Improve `redundant-existence-check` to include function args
I caught myself writing something like this today.

```rego
response := http.send(url, opts) if url
```

Before I realized `if url` is a [redundant-existence-check](https://docs.styra.com/regal/rules/bugs/redundant-existence-check). Would be nice to have Regal tell me that.

### PR DESCRIPTION
**Pull request by anderseknert**
Fixes #1226

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Code looks good. Not sure if we care about `fun(false)`, where the "existence check" isn't really redundant.

**Comment by anderseknert** [comment]
@srenatus not sure I understand. Where's the existence check in `fun(false)`? 🙂

**Comment by srenatus** [comment]
Excuse my brevity, the test in this PR included this rego:
```rego
fun(foo) if {
  foo # line 2
}
```
the "existence check" in line 2 doesn't seem redundant to me if I feed `false` into `fun()`.

**Comment by anderseknert** [comment]
@srenatus ah, gotcha. I'll amend the docs for the rule to mention that case, and how being explicit for that case (e.g. `foo == false`/`foo != false` is a better solution anyway.

**Pull request merged**
